* This Repository is deprecated!

  The clog-cuda repository has been completely integrated into
  [[https://codeberg.org/ormf/clamps][Clamps]] and is developed there. The archive here is only kept for
  historical reasons. This archive will not receive further updates or
  patches. Issues and pull requests will not be looked at here either,
  please submit your patches and issue tickets on the Clamps
  repository on Codeberg, or send them directly via good old email
  patches to the author.* clog-cuda
*** Orm Finnendahl

Widgets for DSP related Guis using [[https://github.com/rabbibotton/clog][clog]] and [[http://incudine.sourceforge.net/][incudine]].
.

** License

gpl 2.0 or later


Copyright (c) 2024 Orm Finnendahl <orm.finnendahl@selma.hfmdk-frankfurt.de>

** Dependencies

   - [[https://github.com/rabbibotton/clog/][clog]]

   - [[https://github.com/titola/incudine][incudine]] 

   -  [[https://github.com/ormf/of-incudine-dsps][of-incudine-dsps]]

   -  [[https://github.com/ormf/cl-refs][cl-refs]]

   -  [[https://github.com/ormf/clog-dsp-widgets][clog-dsp-widgets]]
   
** Install

   - clone all dependencies into =$HOME/quicklisp/local-projects=
   
   - clone this Repository into =$HOME/quicklisp/local-projects=

   - Startup a lisp and issue =(ql:quickload :clog-cuda)=

** Usage

   - see =examples/example.lisp= in this repository
* clog-widgets
*** _Orm Finnendahl <orm.finnendahl@selma.hfmdk-frankfurt.de>_

This is a project to do ... something.

** License

gpl 2.0 or later


Copyright (c) 2024 Orm Finnendahl <orm.finnendahl@selma.hfmdk-frankfurt.de>